In [7]:
import interface.processor

# reload the processor module 
# img_dsfaafdsdfdsads
# 
# 
# 
# 
# dfda
# 
# 
# 
# 
# 
# 
# to ensure the latest version is used
import importlib
importlib.reload(interface.processor)


<module 'interface.processor' from 'd:\\local_mydev\\damage_assessment_pipeline\\app\\interface\\processor.py'>

In [8]:
# params = {
#     'task': 'single_segmentation',
#     'input_file': r"D:\temporal\input\New folder\20_WEEK_5_(_FIELD_A)_md.jpg",
#     'output_dir': r"D:\temporal\input\New folder"
# }

# proc = Processor(params)
# proc.process()

In [9]:
params = {
    'task': 'single_damage_classification'
    ,'model': 'Regnet'
    ,'input_file': r"D:\temporal\input\183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg"
}

proc = interface.processor.Processor(params)
res = proc.run()

print(res['results'])

************** MODEL
Regnet
\\CATALOGUE.CGIARAD.ORG\AcceleratedBreedingInitiative\1.Data\16. Spidermites_AdrianK\models\onnx\regnet_x_32gf_SpidermitesModel.onnx
[9.9609548e-01 1.6642186e-03 1.8798114e-03 3.6055531e-04]
{'0-(No damage)': np.float32(0.9960955), '1-3-(Moderately damaged)': np.float32(0.0016642186), '4-7-(Damaged)': np.float32(0.0018798114), '8-10-(Severely damaged)': np.float32(0.0003605553), 'filepath': 'D:/temporal/input/183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'basename': '183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'damage': '0-(No damage)'}


In [10]:
params = {
    'task': 'single_damage_classification'
    ,'model': 'Resnet18'
    ,'input_file': r"D:\temporal\input\183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg"
}

proc = interface.processor.Processor(params)
res = proc.run()

print(res['results'])

************** MODEL
Resnet18
\\CATALOGUE.CGIARAD.ORG\AcceleratedBreedingInitiative\1.Data\16. Spidermites_AdrianK\models\onnx\resnet18_SpidermitesModel.onnx
[ 0.6719701   0.07059852 -0.08865058 -0.10522906]
{'0-(No damage)': np.float32(0.4040196), '1-3-(Moderately damaged)': np.float32(0.22142674), '4-7-(Damaged)': np.float32(0.18882917), '8-10-(Severely damaged)': np.float32(0.18572447), 'filepath': 'D:/temporal/input/183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'basename': '183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'damage': '0-(No damage)'}


In [11]:
params = {
    'task': 'single_damage_classification'
    ,'model': 'Resnet152'
    ,'input_file': r"D:\temporal\input\183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg"
}

proc = interface.processor.Processor(params)
res = proc.run()

print(res['results'])

************** MODEL
Resnet152
\\CATALOGUE.CGIARAD.ORG\AcceleratedBreedingInitiative\1.Data\16. Spidermites_AdrianK\models\onnx\short_resnet152_SpidermitesModel_44_44.onnx
[ 0.6589184   0.2706642  -0.43970746 -0.44555712]
{'0-(No damage)': np.float32(0.42681172), '1-3-(Moderately damaged)': np.float32(0.28948075), '4-7-(Damaged)': np.float32(0.14226864), '8-10-(Severely damaged)': np.float32(0.14143886), 'filepath': 'D:/temporal/input/183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'basename': '183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'damage': '0-(No damage)'}


In [12]:
params = {
    'task': 'single_damage_classification'
    ,'model': 'Googlenet'
    ,'input_file': r"D:\temporal\input\183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg"
}

proc = interface.processor.Processor(params)
res = proc.run()

print(res['results'])

************** MODEL
Googlenet
\\CATALOGUE.CGIARAD.ORG\AcceleratedBreedingInitiative\1.Data\16. Spidermites_AdrianK\models\onnx\googlenet_SpidermitesModel.onnx
[ 0.3601093   0.85040414 -1.1039641  -0.02791178]
{'0-(No damage)': np.float32(0.28228748), '1-3-(Moderately damaged)': np.float32(0.4609183), '4-7-(Damaged)': np.float32(0.06529089), '8-10-(Severely damaged)': np.float32(0.19150327), 'filepath': 'D:/temporal/input/183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'basename': '183_Week_1_(28th_Aug_-_1st_Sept.)_2023_nd.jpg', 'damage': '1-3-(Moderately damaged)'}
